const default_settings = {
    brick_count: 5,
    initial_block_speed: 3,
    block_velocity_linear: 0.1,
    block_velocity_square: 0,
    block_size: 30,
    brick_height: 40,
    gap_size: 5,
    initial_brick_velocity: 2,
    brick_velocity_linear: 0.01,
    brick_velocity_square: 0.001,
    display_name: "DROPBLOX",
    player_colour: "#212529",
    brick_colour: "#212539",
    canvas_colour: "#D0D0D0",
    number_of_gaps: 1,
    initial_number_of_lives: 1,
    canvas_height: 500,
    canvas_width: 900,
    life_regeneration_rate: 0,
    wall_mode: 1,
};
